// Sample course data shared across all pages
export const coursesData = [
  {
    id: 1,
    title: 'React Fundamentals',
    description: 'Learn the basics of React and build interactive UIs',
    category: 'Frontend',
    icon: '⚛️',
    progress: 45,
    lessons: [
      { id: 1, title: 'Introduction to React', duration: '15 min' },
      { id: 2, title: 'JSX and Rendering', duration: '20 min' },
      { id: 3, title: 'Components and Props', duration: '25 min' },
      { id: 4, title: 'State and Hooks', duration: '30 min' },
      { id: 5, title: 'Event Handling', duration: '20 min' },
    ],
  },
  {
    id: 2,
    title: 'JavaScript ES6+',
    description: 'Master modern JavaScript features and best practices',
    category: 'Programming',
    icon: '🚀',
    progress: 60,
    lessons: [
      { id: 1, title: 'Arrow Functions', duration: '15 min' },
      { id: 2, title: 'Destructuring', duration: '20 min' },
      { id: 3, title: 'Promises and Async/Await', duration: '30 min' },
      { id: 4, title: 'Modules and Imports', duration: '20 min' },
    ],
  },
  {
    id: 3,
    title: 'Web Design with CSS',
    description: 'Create beautiful and responsive web designs',
    category: 'Design',
    icon: '🎨',
    progress: 30,
    lessons: [
      { id: 1, title: 'CSS Basics', duration: '20 min' },
      { id: 2, title: 'Flexbox and Grid', duration: '30 min' },
      { id: 3, title: 'Responsive Design', duration: '25 min' },
      { id: 4, title: 'Animations and Transitions', duration: '25 min' },
      { id: 5, title: 'Tailwind CSS', duration: '20 min' },
    ],
  },
  {
    id: 4,
    title: 'Database Design',
    description: 'Learn SQL and database fundamentals',
    category: 'Backend',
    icon: '🗄️',
    progress: 75,
    lessons: [
      { id: 1, title: 'Relational Databases', duration: '25 min' },
      { id: 2, title: 'SQL Queries', duration: '30 min' },
      { id: 3, title: 'Joins and Relationships', duration: '30 min' },
      { id: 4, title: 'Indexing and Optimization', duration: '25 min' },
    ],
  },
  {
    id: 5,
    title: 'Node.js & Express',
    description: 'Build backend applications with Node.js',
    category: 'Backend',
    icon: '🟢',
    progress: 50,
    lessons: [
      { id: 1, title: 'Node.js Basics', duration: '20 min' },
      { id: 2, title: 'Express Server Setup', duration: '25 min' },
      { id: 3, title: 'Routing and Middleware', duration: '30 min' },
      { id: 4, title: 'REST APIs', duration: '30 min' },
    ],
  },
  {
    id: 6,
    title: 'TypeScript Mastery',
    description: 'Type-safe JavaScript for large-scale applications',
    category: 'Programming',
    icon: '🔷',
    progress: 20,
    lessons: [
      { id: 1, title: 'TypeScript Basics', duration: '20 min' },
      { id: 2, title: 'Interfaces and Types', duration: '25 min' },
      { id: 3, title: 'Generics', duration: '30 min' },
      { id: 4, title: 'Advanced Types', duration: '30 min' },
    ],
  },
]
